services:
  publish:
    build:
      context: "./publish-context"
      dockerfile: "../Dockerfile"
    container_name: quarto-slides-publish
    volumes:
      - "${HOME}/.gitconfig:/root/.gitconfig:ro"
      - "${HOME}/.ssh:/root/.ssh:ro"
    restart: unless-stopped